[build-system]
requires = ["setuptools",
            "wheel"
            ]
build-backend = 'setuptools.build_meta'

[tool.pytest.ini_options]
addopts = [
    "--verbose",
    "--cov=fastspecfit",
    "--cov-report=html",
    ]
