# Generated by Django 3.2.5 on 2022-01-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField(default=-1)),
                ('targetid', models.IntegerField(null=True)),
                ('ra', models.FloatField(null=True)),
                ('dec', models.FloatField(null=True)),
                ('ux', models.FloatField(default=-2.0)),
                ('uy', models.FloatField(default=-2.0)),
                ('uz', models.FloatField(default=-2.0)),
            ],
        ),
    ]
