FROM desihub/fastspecfit-base:1.0

WORKDIR /src

ENV PIP_ROOT_USER_ACTION=ignore

RUN for x in \
    wheel \
    setuptools \
    pytest \
    numpy \
    numba \
    ipython \
    ipykernel \
    ; do pip3 install --break-system-packages $x; done \
    && rm -Rf /root/.cache/pip

COPY test-mpipool /usr/local/bin/test-mpipool
RUN chmod +x /usr/local/bin/test-mpipool

COPY test-mpi-fastspecfit /usr/local/bin/test-mpi-fastspecfit
RUN chmod +x /usr/local/bin/test-mpi-fastspecfit

LABEL Maintainer="John Moustakas jmoustakas@siena.edu"
