# podman-hpc login docker.io
# podman-hpc build --tag desihub/fastspecfit-test --file ./Containerfile-test .
# podman-hpc migrate desihub/fastspecfit-test
# podman-hpc run --rm -it desihub/fastspecfit-test /bin/bash
# srun --ntasks=2 podman-hpc run --rm --mpi --entrypoint= -it desihub/fastspecfit-test /usr/local/bin/test-mpi-fastspecfit --mp=4

FROM desihub/fastspecfit-base:1.0

WORKDIR /src

RUN ln -s "$(which python3)" /usr/bin/python

ENV PIP_ROOT_USER_ACTION=ignore

RUN for x in \
    wheel \
    setuptools \
    pytest \
    numpy \
    numba \
    mpi4py \
    ipython \
    ipykernel \
    ; do pip3 install --break-system-packages $x; done \
    && rm -Rf /root/.cache/pip

COPY test-mpi-fastspecfit /usr/local/bin/test-mpi-fastspecfit
RUN chmod +x /usr/local/bin/test-mpi-fastspecfit

# set prompt and default shell
SHELL ["/bin/bash", "-c"]
ENTRYPOINT ["/bin/bash", "-c"]
CMD ["/bin/bash"]

LABEL Maintainer="John Moustakas jmoustakas@siena.edu"
