#!/usr/bin/env python

from mpi4py.futures import MPIPoolExecutor
import numpy as np

def calculate_pi(n):
    """Calculate Pi using Monte Carlo method."""
    x = np.random.rand(n)
    y = np.random.rand(n)
    inside_circle = (x**2 + y**2) <= 1
    return 4 * np.sum(inside_circle) / n

if __name__ == "__main__":
   mp = 16
   n_points = 100000
   with MPIPoolExecutor(mp) as P:
      chunk_size = n_points // mp

      results = P.map(calculate_pi, [chunk_size] * mp)
      pi_approx = np.mean(list(results))

      if P.is_master():
          print(f"Approximation of pi: {pi_approx}")
