FROM desihub/fastspecfit-base:1.0

WORKDIR /src

ENV PIP_ROOT_USER_ACTION=ignore

RUN for x in \
    wheel \
    setuptools \
    pytest \
    numpy \
    scipy \
    astropy \
    healpy \
    fitsio \
    numba \
    mkl \
    mkl_fft \
    # intel-cmplr-lib-rt \
    # mpi4py \
    seaborn \
    matplotlib \
    ipython \
    ipykernel \
    h5py \
    ; do pip3 install --break-system-packages $x; done \
    && rm -Rf /root/.cache/pip

## install FFT-specific packages
#RUN pip3 install --break-system-packages \
#                 --index-url https://software.repos.intel.com/python/pypi \
#                 --extra-index-url https://pypi.org/simple mkl_fft

# https://gitlab.com/NERSC/python-benchmark/-/tree/main/amd
COPY fakeintel.c /src/fakeintel.c
RUN gcc -shared -fPIC -o /usr/local/lib/libfakeintel.so /src/fakeintel.c \
ENV LD_PRELOAD=/usr/local/lib/libfakeintel.so

ENV DESIUTIL_VERSION 3.4.3
ENV DESIMODEL_VERSION 0.19.2
ENV DESITARGET_VERSION 2.8.0
ENV DESISPEC_VERSION 0.68.1
ENV SPECLITE_VERSION v0.20
ENV FASTSPECFIT_VERSION pure-MPI
#ENV FASTSPECFIT_VERSION 3.1.1

RUN pip3 install --break-system-packages git+https://github.com/desihub/desiutil.git@${DESIUTIL_VERSION}#egg=desiutil
RUN pip3 install --break-system-packages git+https://github.com/desihub/desimodel.git@${DESIMODEL_VERSION}#egg=desimodel
RUN pip3 install --break-system-packages git+https://github.com/desihub/desitarget.git@${DESITARGET_VERSION}#egg=desitarget
RUN pip3 install --break-system-packages git+https://github.com/desihub/desispec.git@${DESISPEC_VERSION}#egg=desispec
RUN pip3 install --break-system-packages git+https://github.com/desihub/speclite.git@${SPECLITE_VERSION}#egg=speclite
RUN pip3 install  --break-system-packages git+https://github.com/desihub/fastspecfit.git@${FASTSPECFIT_VERSION}#egg=fastspecfit

ENV DESI_SPECTRO_REDUX /dvs_ro/cfs/cdirs/desi/spectro/redux
ENV DUST_DIR /dvs_ro/cfs/cdirs/cosmo/data/dust/v0_1
ENV FPHOTO_DIR /dvs_ro/cfs/cdirs/desi/external/legacysurvey/dr9
ENV FTEMPLATES_DIR /dvs_ro/cfs/cdirs/desi/public/external/templates/fastspecfit

# set up the numba cache
ENV HOME /homedir
ENV NUMBA_CACHE_DIR=$HOME/numba_cache

RUN mkdir -p /homedir/numba_cache \
    && chmod -R 777 /homedir*
RUN pytest /usr/local/lib/python3.12/dist-packages/fastspecfit/test/test_fastspecfit.py

LABEL Maintainer="John Moustakas jmoustakas@siena.edu"
