FROM ubuntu:24.04

WORKDIR /src

RUN mkdir -p /src
RUN apt-get -y clean && apt -y update && apt install -y apt-utils && apt -y upgrade

RUN DEBIAN_FRONTEND=noninteractive \
    apt install -y --no-install-recommends \
    build-essential \
    gfortran \
    wget \
    git \
    libbz2-dev \ 
    libgsl-dev \ 
    libssl-dev \
    libcfitsio-dev \
    libcfitsio-bin \
    # libhdf5 needed by h5py
    libhdf5-dev \
    # needed by mpich \
    python3.12 \
    python3.12-dev \
    python3-pip \
    && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

ARG mpich=3.4.3
ARG mpich_prefix=mpich-$mpich

ENV FFLAGS="-fallow-argument-mismatch" \
    FCFLAGS="-fallow-argument-mismatch"

RUN wget --no-check-certificate -nv https://www.mpich.org/static/downloads/$mpich/$mpich_prefix.tar.gz \
    && tar xvzf $mpich_prefix.tar.gz \
    && cd $mpich_prefix \
    && ./configure --with-device=ch4:ofi \
    && make -j 16 \
    && make install \
    && make clean \
    && cd .. \
    && rm -rf $mpich_prefix \
    && rm -f $mpich_prefix.tar.gz

RUN /sbin/ldconfig

# Install Miniconda
ENV CONDA_DIR=/opt/miniconda
ENV PYTHON_VERSION=latest

RUN wget https://repo.anaconda.com/miniconda/Miniconda3-$PYTHON_VERSION-Linux-x86_64.sh -O /tmp/miniconda.sh \
    && bash /tmp/miniconda.sh -b -p $CONDA_DIR \
    && rm /tmp/miniconda.sh

# Update PATH environment variable
ENV PATH="$CONDA_DIR/bin:$PATH"

# Verify Miniconda installation and initialize environment
RUN conda init bash && conda update -n base -c defaults conda -y

# Set default shell to bash
SHELL ["/bin/bash", "-c"]

LABEL Maintainer="John Moustakas jmoustakas@siena.edu"
