name: CI

on:
    push:
        branches:
            - '*'
        tags:
            - '*'
    pull_request:

jobs:
    tests:
        name: Unit tests
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ['3.10', '3.12', '3.14']

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Python dependencies
              run: |
                sudo apt-get update
                sudo apt install libbz2-dev
                python -m pip install --upgrade pip setuptools wheel
                python -m pip install -e ".[test]"
            - name: Verify Installation
              run: pip list
            - name: Set template cache path
              run: echo "FTEMPLATES_CACHE_DIR=$HOME/.cache/fastspecfit-templates" >> $GITHUB_ENV
            - name: Cache template files
              uses: actions/cache@v4
              with:
                path: ${{ env.FTEMPLATES_CACHE_DIR }}
                key: ${{ runner.os }}-fastspecfit-templates-2.1.0
            - name: Run the test
              run: pytest

    coverage:
        name: Test coverage
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ['3.12']

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Python dependencies
              run: |
                sudo apt-get update
                sudo apt install libbz2-dev
                python -m pip install --upgrade pip setuptools wheel
                python -m pip install -e ".[coverage]"
            - name: Set template cache path
              run: echo "FTEMPLATES_CACHE_DIR=$HOME/.cache/fastspecfit-templates" >> $GITHUB_ENV
            - name: Cache template files
              uses: actions/cache@v4
              with:
                path: ${{ env.FTEMPLATES_CACHE_DIR }}
                key: ${{ runner.os }}-fastspecfit-templates-2.1.0
            - name: Run the test with coverage
              run: pytest --cov
            - name: Coveralls
              env:
                GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: coveralls

    docs:
        name: Doc test
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ['3.12']

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Python dependencies
              run: python -m pip install --upgrade pip setuptools wheel && pip install -e ".[doc]"
            - name: Test the documentation
              run: sphinx-build -W --keep-going -b html doc doc/_build/html

    style:
        name: Style check
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest]
                python-version: ['3.12']

        steps:
            - name: Checkout code
              uses: actions/checkout@v4
              with:
                fetch-depth: 0
            - name: Set up Python ${{ matrix.python-version }}
              uses: actions/setup-python@v5
              with:
                python-version: ${{ matrix.python-version }}
            - name: Install Python dependencies
              run: python -m pip install --upgrade pip wheel pycodestyle
            - name: Test the style; failures are allowed
              continue-on-error: true
              run: pycodestyle --count py/fastspecfit
